### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by bkolowitz** [htaox/epic-interconnect#1]
i'm receiving errors during the install as shown in the attached screenshot

![capture](https://cloud.githubusercontent.com/assets/3642617/6096751/b1dd5308-af70-11e4-8143-fa4db0954fd3.PNG)

**Comment by htaox** [comment]
zerorpc-node has a dependency for msgpack 0.1.8 which will fail to compile in Windows.

This was fixed by this  [pull request](https://github.com/msgpack/msgpack-node/pull/16)

But zerorpc-node has not updated their package.json

To resolve this, you can install msgpack separately, ```npm -i msgpack``` (currently, version 0.2.4)
Then copy the entire msgpack folder to zerorpc/node_modules/msgpack

or

update the dependencies in package.json in zerorpc
```"msgpack": "~0.2.4"``` and then run npm install inside the zerorpc folder.
(Make sure you delete the node_modules/msgpack folder first)

Hope this helps.

**Comment by htaox** [comment]
@bkolowitz Are you able to install?  I would like to close this issue.

**Comment by bkolowitz** [comment]
Hi, I got it installed on Linux. Do I need to do something on github for
you to close the issue?

**Comment by htaox** [comment]
That's good to hear.  I'll close the issue.

Date: Sat, 21 Feb 2015 12:37:36 -0800
